//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.NLanguageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NLanguageService.NLanguageServiceSoap")]
    public interface NLanguageServiceSoap {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento text dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeSentimentFromText", ReplyAction="*")]
        WebApplication1.NLanguageService.AnalyzeSentimentFromTextResponse AnalyzeSentimentFromText(WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeSentimentFromText", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSentimentFromTextResponse> AnalyzeSentimentFromTextAsync(WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento path dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeSentimentFromFile", ReplyAction="*")]
        WebApplication1.NLanguageService.AnalyzeSentimentFromFileResponse AnalyzeSentimentFromFile(WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeSentimentFromFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSentimentFromFileResponse> AnalyzeSentimentFromFileAsync(WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento text dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeEntitiesFromText", ReplyAction="*")]
        WebApplication1.NLanguageService.AnalyzeEntitiesFromTextResponse AnalyzeEntitiesFromText(WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeEntitiesFromText", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeEntitiesFromTextResponse> AnalyzeEntitiesFromTextAsync(WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento path dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeEntitiesFromFile", ReplyAction="*")]
        WebApplication1.NLanguageService.AnalyzeEntitiesFromFileResponse AnalyzeEntitiesFromFile(WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeEntitiesFromFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeEntitiesFromFileResponse> AnalyzeEntitiesFromFileAsync(WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento text dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeSyntaxFromText", ReplyAction="*")]
        WebApplication1.NLanguageService.AnalyzeSyntaxFromTextResponse AnalyzeSyntaxFromText(WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeSyntaxFromText", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSyntaxFromTextResponse> AnalyzeSyntaxFromTextAsync(WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento path dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeSyntaxFromFile", ReplyAction="*")]
        WebApplication1.NLanguageService.AnalyzeSyntaxFromFileResponse AnalyzeSyntaxFromFile(WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnalyzeSyntaxFromFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSyntaxFromFileResponse> AnalyzeSyntaxFromFileAsync(WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeSentimentFromTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeSentimentFromText", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequestBody Body;
        
        public AnalyzeSentimentFromTextRequest() {
        }
        
        public AnalyzeSentimentFromTextRequest(WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeSentimentFromTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public AnalyzeSentimentFromTextRequestBody() {
        }
        
        public AnalyzeSentimentFromTextRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeSentimentFromTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeSentimentFromTextResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeSentimentFromTextResponseBody Body;
        
        public AnalyzeSentimentFromTextResponse() {
        }
        
        public AnalyzeSentimentFromTextResponse(WebApplication1.NLanguageService.AnalyzeSentimentFromTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeSentimentFromTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnalyzeSentimentFromTextResult;
        
        public AnalyzeSentimentFromTextResponseBody() {
        }
        
        public AnalyzeSentimentFromTextResponseBody(string AnalyzeSentimentFromTextResult) {
            this.AnalyzeSentimentFromTextResult = AnalyzeSentimentFromTextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeSentimentFromFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeSentimentFromFile", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequestBody Body;
        
        public AnalyzeSentimentFromFileRequest() {
        }
        
        public AnalyzeSentimentFromFileRequest(WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeSentimentFromFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        public AnalyzeSentimentFromFileRequestBody() {
        }
        
        public AnalyzeSentimentFromFileRequestBody(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeSentimentFromFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeSentimentFromFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeSentimentFromFileResponseBody Body;
        
        public AnalyzeSentimentFromFileResponse() {
        }
        
        public AnalyzeSentimentFromFileResponse(WebApplication1.NLanguageService.AnalyzeSentimentFromFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeSentimentFromFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnalyzeSentimentFromFileResult;
        
        public AnalyzeSentimentFromFileResponseBody() {
        }
        
        public AnalyzeSentimentFromFileResponseBody(string AnalyzeSentimentFromFileResult) {
            this.AnalyzeSentimentFromFileResult = AnalyzeSentimentFromFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeEntitiesFromTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeEntitiesFromText", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequestBody Body;
        
        public AnalyzeEntitiesFromTextRequest() {
        }
        
        public AnalyzeEntitiesFromTextRequest(WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeEntitiesFromTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public AnalyzeEntitiesFromTextRequestBody() {
        }
        
        public AnalyzeEntitiesFromTextRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeEntitiesFromTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeEntitiesFromTextResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeEntitiesFromTextResponseBody Body;
        
        public AnalyzeEntitiesFromTextResponse() {
        }
        
        public AnalyzeEntitiesFromTextResponse(WebApplication1.NLanguageService.AnalyzeEntitiesFromTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeEntitiesFromTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnalyzeEntitiesFromTextResult;
        
        public AnalyzeEntitiesFromTextResponseBody() {
        }
        
        public AnalyzeEntitiesFromTextResponseBody(string AnalyzeEntitiesFromTextResult) {
            this.AnalyzeEntitiesFromTextResult = AnalyzeEntitiesFromTextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeEntitiesFromFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeEntitiesFromFile", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequestBody Body;
        
        public AnalyzeEntitiesFromFileRequest() {
        }
        
        public AnalyzeEntitiesFromFileRequest(WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeEntitiesFromFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        public AnalyzeEntitiesFromFileRequestBody() {
        }
        
        public AnalyzeEntitiesFromFileRequestBody(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeEntitiesFromFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeEntitiesFromFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeEntitiesFromFileResponseBody Body;
        
        public AnalyzeEntitiesFromFileResponse() {
        }
        
        public AnalyzeEntitiesFromFileResponse(WebApplication1.NLanguageService.AnalyzeEntitiesFromFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeEntitiesFromFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnalyzeEntitiesFromFileResult;
        
        public AnalyzeEntitiesFromFileResponseBody() {
        }
        
        public AnalyzeEntitiesFromFileResponseBody(string AnalyzeEntitiesFromFileResult) {
            this.AnalyzeEntitiesFromFileResult = AnalyzeEntitiesFromFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeSyntaxFromTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeSyntaxFromText", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequestBody Body;
        
        public AnalyzeSyntaxFromTextRequest() {
        }
        
        public AnalyzeSyntaxFromTextRequest(WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeSyntaxFromTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public AnalyzeSyntaxFromTextRequestBody() {
        }
        
        public AnalyzeSyntaxFromTextRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeSyntaxFromTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeSyntaxFromTextResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeSyntaxFromTextResponseBody Body;
        
        public AnalyzeSyntaxFromTextResponse() {
        }
        
        public AnalyzeSyntaxFromTextResponse(WebApplication1.NLanguageService.AnalyzeSyntaxFromTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeSyntaxFromTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnalyzeSyntaxFromTextResult;
        
        public AnalyzeSyntaxFromTextResponseBody() {
        }
        
        public AnalyzeSyntaxFromTextResponseBody(string AnalyzeSyntaxFromTextResult) {
            this.AnalyzeSyntaxFromTextResult = AnalyzeSyntaxFromTextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeSyntaxFromFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeSyntaxFromFile", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequestBody Body;
        
        public AnalyzeSyntaxFromFileRequest() {
        }
        
        public AnalyzeSyntaxFromFileRequest(WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeSyntaxFromFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        public AnalyzeSyntaxFromFileRequestBody() {
        }
        
        public AnalyzeSyntaxFromFileRequestBody(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnalyzeSyntaxFromFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnalyzeSyntaxFromFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.NLanguageService.AnalyzeSyntaxFromFileResponseBody Body;
        
        public AnalyzeSyntaxFromFileResponse() {
        }
        
        public AnalyzeSyntaxFromFileResponse(WebApplication1.NLanguageService.AnalyzeSyntaxFromFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnalyzeSyntaxFromFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnalyzeSyntaxFromFileResult;
        
        public AnalyzeSyntaxFromFileResponseBody() {
        }
        
        public AnalyzeSyntaxFromFileResponseBody(string AnalyzeSyntaxFromFileResult) {
            this.AnalyzeSyntaxFromFileResult = AnalyzeSyntaxFromFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NLanguageServiceSoapChannel : WebApplication1.NLanguageService.NLanguageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NLanguageServiceSoapClient : System.ServiceModel.ClientBase<WebApplication1.NLanguageService.NLanguageServiceSoap>, WebApplication1.NLanguageService.NLanguageServiceSoap {
        
        public NLanguageServiceSoapClient() {
        }
        
        public NLanguageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NLanguageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NLanguageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NLanguageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.NLanguageService.AnalyzeSentimentFromTextResponse WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeSentimentFromText(WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequest request) {
            return base.Channel.AnalyzeSentimentFromText(request);
        }
        
        public string AnalyzeSentimentFromText(string text) {
            WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequest inValue = new WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequestBody();
            inValue.Body.text = text;
            WebApplication1.NLanguageService.AnalyzeSentimentFromTextResponse retVal = ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeSentimentFromText(inValue);
            return retVal.Body.AnalyzeSentimentFromTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSentimentFromTextResponse> WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeSentimentFromTextAsync(WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequest request) {
            return base.Channel.AnalyzeSentimentFromTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSentimentFromTextResponse> AnalyzeSentimentFromTextAsync(string text) {
            WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequest inValue = new WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeSentimentFromTextRequestBody();
            inValue.Body.text = text;
            return ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeSentimentFromTextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.NLanguageService.AnalyzeSentimentFromFileResponse WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeSentimentFromFile(WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequest request) {
            return base.Channel.AnalyzeSentimentFromFile(request);
        }
        
        public string AnalyzeSentimentFromFile(string path) {
            WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequest inValue = new WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequestBody();
            inValue.Body.path = path;
            WebApplication1.NLanguageService.AnalyzeSentimentFromFileResponse retVal = ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeSentimentFromFile(inValue);
            return retVal.Body.AnalyzeSentimentFromFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSentimentFromFileResponse> WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeSentimentFromFileAsync(WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequest request) {
            return base.Channel.AnalyzeSentimentFromFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSentimentFromFileResponse> AnalyzeSentimentFromFileAsync(string path) {
            WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequest inValue = new WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeSentimentFromFileRequestBody();
            inValue.Body.path = path;
            return ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeSentimentFromFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.NLanguageService.AnalyzeEntitiesFromTextResponse WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeEntitiesFromText(WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequest request) {
            return base.Channel.AnalyzeEntitiesFromText(request);
        }
        
        public string AnalyzeEntitiesFromText(string text) {
            WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequest inValue = new WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequestBody();
            inValue.Body.text = text;
            WebApplication1.NLanguageService.AnalyzeEntitiesFromTextResponse retVal = ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeEntitiesFromText(inValue);
            return retVal.Body.AnalyzeEntitiesFromTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeEntitiesFromTextResponse> WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeEntitiesFromTextAsync(WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequest request) {
            return base.Channel.AnalyzeEntitiesFromTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeEntitiesFromTextResponse> AnalyzeEntitiesFromTextAsync(string text) {
            WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequest inValue = new WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeEntitiesFromTextRequestBody();
            inValue.Body.text = text;
            return ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeEntitiesFromTextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.NLanguageService.AnalyzeEntitiesFromFileResponse WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeEntitiesFromFile(WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequest request) {
            return base.Channel.AnalyzeEntitiesFromFile(request);
        }
        
        public string AnalyzeEntitiesFromFile(string path) {
            WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequest inValue = new WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequestBody();
            inValue.Body.path = path;
            WebApplication1.NLanguageService.AnalyzeEntitiesFromFileResponse retVal = ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeEntitiesFromFile(inValue);
            return retVal.Body.AnalyzeEntitiesFromFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeEntitiesFromFileResponse> WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeEntitiesFromFileAsync(WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequest request) {
            return base.Channel.AnalyzeEntitiesFromFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeEntitiesFromFileResponse> AnalyzeEntitiesFromFileAsync(string path) {
            WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequest inValue = new WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeEntitiesFromFileRequestBody();
            inValue.Body.path = path;
            return ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeEntitiesFromFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.NLanguageService.AnalyzeSyntaxFromTextResponse WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeSyntaxFromText(WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequest request) {
            return base.Channel.AnalyzeSyntaxFromText(request);
        }
        
        public string AnalyzeSyntaxFromText(string text) {
            WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequest inValue = new WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequestBody();
            inValue.Body.text = text;
            WebApplication1.NLanguageService.AnalyzeSyntaxFromTextResponse retVal = ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeSyntaxFromText(inValue);
            return retVal.Body.AnalyzeSyntaxFromTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSyntaxFromTextResponse> WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeSyntaxFromTextAsync(WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequest request) {
            return base.Channel.AnalyzeSyntaxFromTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSyntaxFromTextResponse> AnalyzeSyntaxFromTextAsync(string text) {
            WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequest inValue = new WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeSyntaxFromTextRequestBody();
            inValue.Body.text = text;
            return ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeSyntaxFromTextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.NLanguageService.AnalyzeSyntaxFromFileResponse WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeSyntaxFromFile(WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequest request) {
            return base.Channel.AnalyzeSyntaxFromFile(request);
        }
        
        public string AnalyzeSyntaxFromFile(string path) {
            WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequest inValue = new WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequestBody();
            inValue.Body.path = path;
            WebApplication1.NLanguageService.AnalyzeSyntaxFromFileResponse retVal = ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeSyntaxFromFile(inValue);
            return retVal.Body.AnalyzeSyntaxFromFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSyntaxFromFileResponse> WebApplication1.NLanguageService.NLanguageServiceSoap.AnalyzeSyntaxFromFileAsync(WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequest request) {
            return base.Channel.AnalyzeSyntaxFromFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.NLanguageService.AnalyzeSyntaxFromFileResponse> AnalyzeSyntaxFromFileAsync(string path) {
            WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequest inValue = new WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequest();
            inValue.Body = new WebApplication1.NLanguageService.AnalyzeSyntaxFromFileRequestBody();
            inValue.Body.path = path;
            return ((WebApplication1.NLanguageService.NLanguageServiceSoap)(this)).AnalyzeSyntaxFromFileAsync(inValue);
        }
    }
}
