//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceDemo.MyWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebService.CalculatorServiceSoap")]
    public interface CalculatorServiceSoap {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento MessageResult dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Message", ReplyAction="*")]
        WebServiceDemo.MyWebService.MessageResponse Message(WebServiceDemo.MyWebService.MessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Message", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceDemo.MyWebService.MessageResponse> MessageAsync(WebServiceDemo.MyWebService.MessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        decimal Add(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AddAsync(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        decimal Sub(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> SubAsync(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mul", ReplyAction="*")]
        decimal Mul(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> MulAsync(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Div", ReplyAction="*")]
        decimal Div(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Div", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> DivAsync(decimal a, decimal b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Message", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceDemo.MyWebService.MessageRequestBody Body;
        
        public MessageRequest() {
        }
        
        public MessageRequest(WebServiceDemo.MyWebService.MessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MessageRequestBody {
        
        public MessageRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceDemo.MyWebService.MessageResponseBody Body;
        
        public MessageResponse() {
        }
        
        public MessageResponse(WebServiceDemo.MyWebService.MessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MessageResult;
        
        public MessageResponseBody() {
        }
        
        public MessageResponseBody(string MessageResult) {
            this.MessageResult = MessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorServiceSoapChannel : WebServiceDemo.MyWebService.CalculatorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceSoapClient : System.ServiceModel.ClientBase<WebServiceDemo.MyWebService.CalculatorServiceSoap>, WebServiceDemo.MyWebService.CalculatorServiceSoap {
        
        public CalculatorServiceSoapClient() {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceDemo.MyWebService.MessageResponse WebServiceDemo.MyWebService.CalculatorServiceSoap.Message(WebServiceDemo.MyWebService.MessageRequest request) {
            return base.Channel.Message(request);
        }
        
        public string Message() {
            WebServiceDemo.MyWebService.MessageRequest inValue = new WebServiceDemo.MyWebService.MessageRequest();
            inValue.Body = new WebServiceDemo.MyWebService.MessageRequestBody();
            WebServiceDemo.MyWebService.MessageResponse retVal = ((WebServiceDemo.MyWebService.CalculatorServiceSoap)(this)).Message(inValue);
            return retVal.Body.MessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceDemo.MyWebService.MessageResponse> WebServiceDemo.MyWebService.CalculatorServiceSoap.MessageAsync(WebServiceDemo.MyWebService.MessageRequest request) {
            return base.Channel.MessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceDemo.MyWebService.MessageResponse> MessageAsync() {
            WebServiceDemo.MyWebService.MessageRequest inValue = new WebServiceDemo.MyWebService.MessageRequest();
            inValue.Body = new WebServiceDemo.MyWebService.MessageRequestBody();
            return ((WebServiceDemo.MyWebService.CalculatorServiceSoap)(this)).MessageAsync(inValue);
        }
        
        public decimal Add(decimal a, decimal b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<decimal> AddAsync(decimal a, decimal b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public decimal Sub(decimal a, decimal b) {
            return base.Channel.Sub(a, b);
        }
        
        public System.Threading.Tasks.Task<decimal> SubAsync(decimal a, decimal b) {
            return base.Channel.SubAsync(a, b);
        }
        
        public decimal Mul(decimal a, decimal b) {
            return base.Channel.Mul(a, b);
        }
        
        public System.Threading.Tasks.Task<decimal> MulAsync(decimal a, decimal b) {
            return base.Channel.MulAsync(a, b);
        }
        
        public decimal Div(decimal a, decimal b) {
            return base.Channel.Div(a, b);
        }
        
        public System.Threading.Tasks.Task<decimal> DivAsync(decimal a, decimal b) {
            return base.Channel.DivAsync(a, b);
        }
    }
}
